londonbitdevs/londonbitdevs-website

- assets/css/style.scss
Makes a visual distinction from bitdevs.org
> Change link color to blue

- _posts/2023-03-01-socratic-seminar-22.md
27050 is in draft, not merged - whoops. Thanks @dergoegge for spotting.
> fix #27050 not being merged

- _posts/2023-03-29-socratic-seminar-23.md
Reorganized the structure based on https://raw.githubusercontent.com/BitDevsNYC/BitDevsNYC.github.io/master/_posts/_template.md but with less subtopics.
> Add Socratic 23

- _posts/_template.md
Template is largely based on https://raw.githubusercontent.com/BitDevsNYC/BitDevsNYC.github.io/master/_posts/_template.md but simplified a bit.
> Add empty post template

- _posts/2023-05-03-socratic-seminar-24.md
> Add Socratic #24

- _posts/2023-06-28-socratic-seminar-26.md
> Add Socratic 26

- _posts/2023-08-30-socratic-seminar-27.md
> Add Socratic 27

- _posts/2023-09-27-socratic-seminar-28.md
> Add Socratic 28 2023-09-27

- _posts/2023-03-29-socratic-seminar-23.md
- _posts/2023-06-28-socratic-seminar-26.md
- _posts/2023-09-27-socratic-seminar-28.md
- _posts/2023-10-25-socratic-seminar-29.md
- _posts/_template.md
> Add Socratic 29

- _posts/2023-11-29-socratic-seminar-30.md
> Add Socratic 30

- _posts/2024-01-31-socratic-seminar-31.md
> Add Socratic 31

- _posts/_template.md
Since Delving Bitcoin is becoming a regular thing to report on, add it to template.
Also update ML link to the new Google Groups.
> Update template: add Delving, update, ML

- _posts/2024-01-31-socratic-seminar-31.md
- _posts/2024-03-13-socratic-seminar-32.md
- _posts/_template.md
> Add Socratic 32

- _posts/2024-05-29-socratic-seminar-34.md
> Add Socratic 34

- _posts/2024-07-31-socratic-seminar-36.md
> Add Socratic 36

- _posts/2024-08-28-socratic-seminar-37.md
> Add Socratic 37

- _posts/2024-09-24-socratic-seminar-38.md
> Add Socratic 38

- _posts/2024-10-30-socratic-seminar-39.md
> Add Socratic 39

- _posts/2025-03-26-socratic-seminar-40.md
> Add Socratic 40

- _posts/2025-04-30-socratic-seminar-41.md
> Add Socratic 41

- _posts/2025-06-25-socratic-seminar-43.md
> Add Socratic 43

- _posts/2025-07-30-socratic-seminar-44.md
> Add Socratic 44

- _posts/2025-08-27-socratic-seminar-45.md
> Add Socratic 45
